

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogify_web
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:postgres@db:5432
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - db
      - redis

  sidekiq:
    build:
      context: .
    container_name: blogify_sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:postgres@db:5432
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: blogify_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: blogify_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  bundle:
